[project]
version = "1.0.0"
name = "simple-cli"
description = "An example cli app that's very simple."
authors = [
    {name = "Goldy", email = "goldy@example.com"}
]
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.9"
dependencies = [
    "mov-core"
]